defaults:
  - _self_

model:
  input_dim: 1
  output_dim: 2
  latent_dim: 256
  hidden_dim: 256
  num_heads: 4
  dropout_rate: 0.2
  learning_rate: 1e-3

training:
  num_steps: 1000
  batch_size: 64
  rng_seed: 0

hydra:
  job_logging:
    root:
      level: WARNING  #
  output_subdir: null 
